twitter_bearer_token = "AAAAAAAAAAAAAAAAAAAAALsQ3wEAAAAAUXph5Lp9IgndkKCJ1Qe%2FM3psotE%3DM9R9LKS5hKCck2K4lPbuWNlJc5zmgUPt5s13k4HgO8cOEIu0xx"

# This is your Streamlit secrets file.
# Replace the placeholder text with your actual API credentials.
# Do not share this file or commit it to a public GitHub repository.

[twitter]
api_key = "9cmmEfuTupk9QKlhvkWUWU7xe"
api_secret = "ZhvlR11UUaLekGgwZ0qplulX4o2jb9Tj4Hs2sUBMfDUP6xKwtl"
access_token = "1368203703732248579-lAKxRvwtW4WPW8Tc9dxy9Vqus5pn9t"
access_secret = "JKs6nv7UcFnu4qXvJjNZgxeHWLlgKxAaDQh70DX5EqPE5"
bearer_token = "AAAAAAAAAAAAAAAAAAAAALsQ3wEAAAAAUXph5Lp9IgndkKCJ1Qe%2FM3psotE%3DM9R9LKS5hKCck2K4lPbuWNlJc5zmgUPt5s13k4HgO8cOEIu0xx"

[reddit]
client_id = "qmSrf7HH5NlGuJ1DSiVxEg"
client_secret = "fQm-DAEqTUFZ7KasmoP90xtaQgC04w"
user_agent = "myredditapp by u/govindchudari"

[youtube]
api_key = "AIzaSyCa_SH2jtrhcRxZnOdmG2gYIs3EkK38b00"
